import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import About from './About';
import Blog from './Blog';
import Homepage from './Home';

const Home: NextPage = () => {
  return (
    <div className="container flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Homepage />
    </div>
  );
};

export default Home;
