name: Test React

on:
  push:
    branches: [ "master" ]

  workflow_call:
    secrets:
      REACT_APP_PROXY_HOST:
        required: true
      REACT_APP_BACKEND_PROXY_HOST:
        required: true
      REACT_APP_FIREBASE_APIKEY:
        required: true
      REACT_APP_FIREBASE_AUTH_DOMAIN:
        required: true
      REACT_APP_FIREBASE_PROJECT_ID:
        required: true
      REACT_APP_FIREBASE_STORAGE_BUCKET:
        required: true
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID:
        required: true
      REACT_APP_FIREBASE_APPID:
        required: true
      REACT_APP_FIREBASE_MEASUREMENT_ID:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build the app
      run: |
        npm run build --if-present
    - name: Run Component Tests
      run: |
        npm run jest
      env:
        REACT_APP_PROXY_HOST: ${{ secrets.REACT_APP_PROXY_HOST }}
        REACT_APP_BACKEND_PROXY_HOST: ${{ secrets.REACT_APP_BACKEND_PROXY_HOST }}
        REACT_APP_FIREBASE_APIKEY: ${{ secrets.REACT_APP_FIREBASE_APIKEY }}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
        REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_FIREBASE_APPID }}
        REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
    - name: Start the app
      run: |
        npm run start &
        npx wait-on --timeout 6000